from random import randint
num1 = randint(0, 10)
num2 = randint(0, 10)
num3 = randint(0, 10)
num4 = randint(0, 10)
num5 = randint(0, 10)
tup = (num1, num2, num3, num4, num5)
print(tup)
print(f'O maior é {max(tup)}')
print(f'O menor é {min(tup)}')
